
# Networks ############################################################################################################

networks:
  cardano:
    name: cardano
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

# Services ############################################################################################################

services:

  # Relay -------------------------------------------------------------------------------------------------------------

  relay:
    image: nessusio/cardano-node:dev
    container_name: relay
    hostname: relay
    networks:
      cardano:
    ports:
      - "3001:3001"
    environment:
      CARDANO_TOPOLOGY: '{
          "Producers": [
            {
              "addr": "relays-new.cardano-mainnet.iohk.io",
              "port": 3001,
              "valency": 1
            },
            {
              "addr": "xxx.xxx.xxx.xxx",
              "port": 3001,
              "valency": 1
            }
          ]
        }'
      CARDANO_CUSTOM_PEERS: "xxx.xxx.xxx.xxx:3001"
      CARDANO_UPDATE_TOPOLOGY: "true"
    command: "run"
    volumes:
      - /mnt/disks/data00:/opt/cardano/data

  # Monit -------------------------------------------------------------------------------------------------------------

  monit:
    image: nessusio/monit
    container_name: monit
    hostname: ada01rl
    networks:
      cardano:
    command: "-Iv"
    volumes:
      - monit-config:/etc/monit.d

  # NGINX -------------------------------------------------------------------------------------------------------------

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    networks:
      cardano:
    ports:
      - "12798:80"
    volumes:
      - nginx-config:/etc/nginx:ro

# Volumes #############################################################################################################

volumes:
  monit-config:
    external: true
  nginx-config:
    external: true
