
version: "3.9"

# Services ############################################################################################################

services:

  # Relay -------------------------------------------------------------------------------------------------------------

  cardano-node:
    image: nessusio/cardano-node:${CARDANO_NODE_VERSION:-1.25.1}
    restart: on-failure
    ports:
      - ${NODE_PORT:-3001}:3001
    command: "run"
    volumes:
      - node-data:/opt/cardano/data
      - node-ipc:/opt/cardano/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # Postgres ----------------------------------------------------------------------------------------------------------

  postgres:
    image: postgres:${POSTGRES_VERSION:-13.2}
    restart: on-failure
    environment:
      POSTGRES_DB_FILE: "/run/secrets/postgres_db"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_password"
      POSTGRES_USER_FILE: "/run/secrets/postgres_user"
      POSTGRES_LOGGING: "true"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # Cardano DB Sync ---------------------------------------------------------------------------------------------------

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-8.0.0}
    restart: on-failure
    environment:
      NETWORK: "${NETWORK:-mainnet}"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      EXTENDED: "true"
    volumes:
      - db-sync-data:/var/lib/cdbsync
      - node-ipc:/node-ipc
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    depends_on:
      - postgres
      - cardano-node
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# Secrets #############################################################################################################

secrets:
  postgres_db:
    file: ~/cardano/secrets/postgres_db
  postgres_password:
    file: ~/cardano/secrets/postgres_password
  postgres_user:
    file: ~/cardano/secrets/postgres_user

# Volumes #############################################################################################################

volumes:
  db-sync-data:
  postgres:
  node-ipc:
  node-data:
    external: true
    name: node-data
