
version: "3.9"

# Services ############################################################################################################

services:

  # Relay -------------------------------------------------------------------------------------------------------------

  relay:
    image: nessusio/cardano-node:1.25.1
    ports:
      - 3001:3001
    command: "run"
    volumes:
      - node-data:/opt/cardano/data
      - node-ipc:/opt/cardano/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # Postgres ----------------------------------------------------------------------------------------------------------

  postgres:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_DB_FILE: "/run/secrets/postgres_db"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_password"
      POSTGRES_USER_FILE: "/run/secrets/postgres_user"
      POSTGRES_LOGGING: "true"
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # Cardano DB Sync ---------------------------------------------------------------------------------------------------

  cardano-db-sync:
    image: inputoutput/cardano-db-sync
    environment:
      NETWORK: "${NETWORK:-mainnet}"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      EXTENDED: "true"
    depends_on:
      - postgres
      - relay
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - db-sync-data:/var/lib/cdbsync
      - node-ipc:/node-ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# Secrets #############################################################################################################

secrets:
  postgres_db:
    file: ~/cardano/secrets/postgres_db
  postgres_password:
    file: ~/cardano/secrets/postgres_password
  postgres_user:
    file: ~/cardano/secrets/postgres_user

# Volumes #############################################################################################################

volumes:
  db-sync-data:
  postgres:
  node-ipc:
  node-data:
    external: true
