
version: "3.9"

# Services ############################################################################################################

services:

  # Postgres ----------------------------------------------------------------------------------------------------------

  postgres:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_DB_FILE: "/run/secrets/postgres_db"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_password"
      POSTGRES_USER_FILE: "/run/secrets/postgres_user"
      POSTGRES_LOGGING: "true"
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# Secrets #############################################################################################################

secrets:
  postgres_db:
    file: ~/cardano/secrets/postgres_db
  postgres_password:
    file: ~/cardano/secrets/postgres_password
  postgres_user:
    file: ~/cardano/secrets/postgres_user

# Volumes #############################################################################################################

volumes:
  postgres:
